#!/usr/bin/env bash
# stop_infinity.sh

# Find the process ID (PID) of the 4-to_infinity_and_beyond process
# If the process is running, terminate it
PID=$(pgrep 4-to_infinity_and_beyond)

if [ -n "$PID" ]; then
    kill "$PID"
    echo "Process 4-to_infinity_and_beyond (PID $PID) has been terminated."
else
    echo "Process 4-to_infinity_and_beyond is not currently running."
ifi

