#!/usr/bin/env bash
# 67-stop_me_if_you_can

# Function to handle SIGTERM (Ctrl+C)
handle_sigterm() {
    echo "I am invincible!!!"
    exit 0
}

# Register the SIGTERM handler
trap handle_sigterm SIGTERM

# Infinite loop
while true; do
    echo "To infinity and beyond"
    sleep 2
done
